### PR TITLE
Add more detail around the Windows bundle command prompt on launch

### PR DESCRIPTION
**Pull request by DragaDoncila**
- Added a bit more detail for users about the command prompt showing up on Windows when you launch from bundled app
- Add screenshot to draw the eye
- Move above the instructions to launch - maybe this is a bit controversial but I know my user immediately launched from start menu and didn't read any further so they missed the bit about the terminal window. Happy to switch around again if people think the flow of information is wrong

### CODE REVIEW

**Review by GenevieveBuckley — APPROVED** [review]
Looks good to me!

**Comment by GenevieveBuckley** [comment]
I'll leave this open for another day or so in case anyone else wants to comment.  Please ping us @DragaDoncila  if it's been longer than that & I've forgotten to come back and merge this.

**Review by jni — APPROVED** [review]
Great!

**Comment by GenevieveBuckley** [comment]
Thank you @DragaDoncila 🎉

**Pull request merged**
