### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by Mishrasubha**
Changed the url of contributing guideline

### CODE REVIEW

**Comment by jni** [comment]
Thank you @Mishrasubha! I'll just let @sofroniewn or @kne42 double check this.

**Comment by Mishrasubha** [comment]
Heya. There's still a problem in the hyperlinks "getting started" and "installing napari". Maybe because it is given as "./getting_started" and "./installation" but they are not at the same directory as index.md, I am not sure about that.

**Comment by kne42** [comment]
Ah yes, looks like I forgot to change those. They should be `./fundamentals/{getting_started,installation}`

**Comment by Mishrasubha** [comment]
@kne42  I made the following changes :)

**Comment by kne42** [comment]
@Mishrasubha great, thank you! I'll merge now :)

**Pull request merged**
